#!/bin/bash

set -ex

mkdir -p .ruby
cd .ruby

curl -O http://d6r77u77i8pq3.cloudfront.net/releases/traveling-ruby-20150715-2.2.2-linux-x86_64.tar.gz
tar xf traveling-ruby-20150715-2.2.2-linux-x86_64.tar.gz
rm -f traveling-ruby-20150715-2.2.2-linux-x86_64.tar.gz
